
INSERT INTO listings (user_id, title, description, price, img, is_sold) VALUES (1, 'The Incredible Hulk', 'hulk smash', 3500, 'https://miro.medium.com/max/1400/0*XbkhdmnwCKiu4SIs.jpg', FALSE);
INSERT INTO listings (user_id, title, description, price, img, is_sold) VALUES (8, 'Call Of Duty', 'shooty shooty bang bang', 5000, 'https://news.xbox.com/en-us/wp-content/uploads/sites/2/2022/06/Call-of-Duty-Modern-Warfare-II_Reveal_X1_Wire_Hero_1920x1080-b5aea4e5ca6046ac478e.jpg', FALSE);
INSERT INTO listings (user_id, title, description, price, img, is_sold) VALUES (3, 'Super Smash Bros', 'lets get super smash bros!', 10000, 'https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/ncom/en_US/games/switch/s/super-smash-bros-ultimate-switch/hero', FALSE);
INSERT INTO listings (user_id, title, description, price, img, is_sold) VALUES (6, 'NHL 2022', 'go canucks go', 5000, 'https://media.contentapi.ea.com/content/dam/ea/nhl/nhl-22/common/buy-page/nhl22-featured-image-16x9.jpg.adapt.crop191x100.1200w.jpg', FALSE);
INSERT INTO listings (user_id, title, description, price, img, is_sold) VALUES (5, 'Spider Man', 'stick stick stick', 4500, 'https://m.media-amazon.com/images/I/81mliotBKzL._AC_SX425_.jpg', FALSE);
INSERT INTO listings (user_id, title, description, price, img, is_sold) VALUES (3, 'Mario Party', 'paaaaaarrttyyy', 6000, 'https://assets1.ignimgs.com/2019/05/22/mario-party-9---button-1558566997850.jpg', FALSE);
INSERT INTO listings (user_id, title, description, price, img, is_sold) VALUES (4, 'Halo', 'no, not that beyonce song', 5000, 'https://compass-ssl.xbox.com/assets/9c/94/9c944d9c-7ef1-4b46-9f68-9b02966d3993.jpg?n=Halo-Infinite_GLP-Page-Hero-0_1083x609.jpg', FALSE);
INSERT INTO listings (user_id, title, description, price, img, is_sold) VALUES (9, 'God Of War', 'Kratos.. nuff said', 7000, 'http://blog.bestbuy.ca/wp-content/uploads/2018/04/GOW-OG-image.jpg', FALSE);
INSERT INTO listings (user_id, title, description, price, img, is_sold) VALUES (5, 'Grand Theft Auto', 'okayish soundtrack', 4000, 'https://m.media-amazon.com/images/M/MV5BMTAyYWYyOTMtNmUzNS00NzNjLTkyZTUtZjhlZjMzYzJmNzM5XkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_FMjpg_UX1000_.jpg', FALSE);
INSERT INTO listings (user_id, title, description, price, img, is_sold) VALUES (10, 'Dark Souls', 'good luck', 5000, 'https://image.api.playstation.com/gs2-sec/appkgo/prod/CUSA08495_00/4/i_e1d39aec96b1583322c0c83a100142424b2dadd351510fcf0f2c3eed02830576/i/icon0.png', FALSE);

